version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: homiq_pms_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: database
      POSTGRES_DB: homiq_pms
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
